// This code is generated by Google AI
//
import type { Directive, DirectiveBinding } from 'vue';

const transitionDuration = 0.2; // seconds

// Use a WeakMap to securely store overlay references without polluting the DOM element
const overlayMap = new WeakMap<HTMLElement, HTMLDivElement>();

const toggleDim = (el: HTMLElement, shouldDim: boolean): void =>
{
    const overlay = overlayMap.get (el);
    if (overlay)
    {
        if (shouldDim)
        {
            // 1. Show the element visually but keep transparent
            overlay.style.display = 'block';
            // 2. Force a DOM reflow so the transition registers
            overlay.offsetHeight;
            // 3. Fade in
            overlay.style.opacity = '1';
        }
        else
        {
            // 1. Fade out
            overlay.style.opacity = '0';
        
            // 2. Hide from DOM layout after the animation ends (200ms)
            setTimeout(() => 
            {
                // Only hide if the state hasn't flipped back to true during the fade out
                if (overlay.style.opacity === '0')
                {
                    overlay.style.display = 'none';
                }
            }, transitionDuration * 1000);
        }
    }
}

const vDim: Directive<HTMLElement, boolean> = 
{
    mounted (el: HTMLElement, binding: DirectiveBinding<boolean>)
    {
        // Force the element into a relative positioning context
        el.style.position = 'relative';

        // Create the overlay element
        const overlay = document.createElement('div');
        overlay.className = 'v-dim-overlay';

        // Mix the background variable with transparency (e.g., 60% background color, 40% transparent)
        const dynamicBackground = 'color-mix(in srgb, var(--color-background) 60%, transparent)'

        Object.assign (overlay.style, 
        {
            position: 'absolute',
            top: '0',
            left: '0',
            width: '100%',
            height: '100%',
            backgroundColor: dynamicBackground,
            pointerEvents: 'auto',
            zIndex: '999',
            display: 'none',
            transition: `opacity ${transitionDuration}s ease`
        });

        // Append and cache the reference
        el.appendChild (overlay);
        overlayMap.set (el, overlay);

        // Set initial state
        toggleDim (el, binding.value);
    },

    updated (el: HTMLElement, binding: DirectiveBinding<boolean>)
    {
        if (binding.value !== binding.oldValue)
        {
            toggleDim (el, binding.value);
        }
    },

    unmounted (el: HTMLElement)
    {
        const overlay = overlayMap.get (el);
        if (overlay)
        {
            overlay.remove();
            overlayMap.delete (el);
        }
    }
}

export default vDim
