services:
  x1monitor:
    container_name: x1monitor
    hostname: x1monitor
    build:
      context: .
      args: 
        API_HOST: 192.168.0.13
        API_PORT: 4000
    image: x1monitor
    env_file: "docker.env"
    environment:
      NODE_ENV: production
    ports:
      - 5005:5005
      - 4000:4000
      - 9999:9999
    networks:
      - x1monitor
      
networks:
  x1monitor:
    name: x1monitor
    driver: bridge
