services:
  bambu-monitor:
    container_name: bambu-monitor
    hostname: bambu-monitor
    build:
      context: .
    image: bambu-monitor
    env_file: "docker.env"
    environment:
      NODE_ENV: production
    volumes:
      - /volume1/docker/bambu-monitor/projectArchive/:/usr/src/app/projectArchive
    ports:
      - 5005:5005
      - 4000:4000
      - 9999:9999
    networks:
      - bambu-monitor

networks:
  bambu-monitor:
    name: bambu-monitor
    driver: bridge
