# syntax=docker/dockerfile:1
ARG NODE_VERSION=18.12.1

FROM node:${NODE_VERSION}-alpine

RUN apk update && apk add ffmpeg

# Use production node environment by default.
ENV NODE_ENV production

WORKDIR /usr/src/app

COPY package.json .
COPY ./dist .

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
# Leverage a bind mounts to package.json and package-lock.json to avoid having to copy them into
# into this layer.
# RUN --mount=type=bind,source=package.json,target=package.json \
#     --mount=type=bind,source=package-lock.json,target=package-lock.json \
#     --mount=type=cache,target=/root/.npm \
#     npm ci --omit=dev

RUN npm i --omit=dev


# Expose the port that the application listens on.
EXPOSE 5005 9999

# Run the application.
CMD node index.js
